[workspace]
members = ["apps/api"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.90"

[workspace.dependencies]
axum = "0.8.6"
argon2 = "0.5.3"
base64 = "0.22.1"
async-trait = "0.1.89"
aws-config = "1.5.17"
aws-credential-types = "1.2.1"
aws-sdk-s3 = "1.67.0"
chrono-tz = "0.10.4"
chrono = { version = "0.4.41", default-features = false, features = ["clock", "std"] }
clap = { version = "4.5.47", features = ["derive"] }
lettre = { version = "0.11.19", default-features = false, features = ["builder", "smtp-transport", "tokio1-native-tls"] }
hmac = "0.12.1"
rand = "0.9.2"
rust_decimal = { version = "1.39.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sqlx = { version = "0.8.6", default-features = false, features = ["chrono", "macros", "migrate", "postgres", "runtime-tokio-rustls", "rust_decimal", "uuid"] }
sha2 = "0.10.9"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["macros", "net", "rt-multi-thread", "signal", "time"] }
tower = { version = "0.5.2", features = ["util"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "json"] }
utoipa = { version = "5.5.0", features = ["chrono", "uuid"] }
uuid = { version = "1.18.0", features = ["serde", "v4"] }
url = "2.5.8"
