/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve the current account through live Appwrite session validation */
        get: operations["getAuthenticatedSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/money-memos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create confirmed memo or resolve durable retry */
        post: operations["createMoneyMemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/money-memos/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List, search, and filter active or archived memos
         * @description POST keeps search content out of URLs. Pending deletion is never valid here.
         */
        post: operations["queryMoneyMemos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/money-memos/{memoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memoId: components["parameters"]["MemoId"];
            };
            cookie?: never;
        };
        /** Read owned active or archived memo */
        get: operations["getMoneyMemo"];
        /** Replace editable fields atomically using expected revision */
        put: operations["editMoneyMemo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/money-memos/{memoId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive an active memo idempotently */
        post: operations["archiveMoneyMemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/money-memos/{memoId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an archived memo idempotently */
        post: operations["restoreArchivedMoneyMemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/money-memos/{memoId}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a memo to Recently Deleted with fixed 30-day deadline */
        post: operations["requestMoneyMemoDeletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recently-deleted/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Page unexpired pending-deletion memos; no search or filters */
        post: operations["queryRecentlyDeleted"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recently-deleted/{memoId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an unexpired Recently Deleted memo */
        post: operations["restoreDeletedMoneyMemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recently-deleted/{memoId}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Permanently purge after second explicit confirmation */
        post: operations["purgeMoneyMemoNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/labels/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List owner-scoped Category or Money Space labels */
        post: operations["queryLabels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create active Category or Money Space label */
        post: operations["createLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/labels/{labelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelId: components["parameters"]["LabelId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Rename label in place using expected revision */
        put: operations["renameLabel"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/labels/{labelId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate label idempotently */
        post: operations["deactivateLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/labels/{labelId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate label idempotently */
        post: operations["reactivateLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/labels/{labelId}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Permanently delete an unreferenced label */
        post: operations["permanentlyDeleteLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports/money-memos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build one accepted-instant export */
        post: operations["exportMoneyMemos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reference/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return immutable v1 supported ISO 4217 codes and minor-unit scales */
        get: operations["getSupportedCurrencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthenticatedSession: {
            /** @description Current Appwrite account ID; locally transformed before durable draft use. */
            accountId: string;
        };
        /** @enum {string} */
        MoneyMemoType: "income" | "expense";
        /** @enum {string} */
        PlannedStatus: "planned" | "unplanned";
        /** @enum {string} */
        Purpose: "personal" | "work" | "mixed";
        /** @enum {string} */
        LifecycleStatus: "active" | "archived" | "pending_deletion";
        /** @enum {string} */
        LabelKind: "category" | "money_space";
        /** @enum {string} */
        LabelState: "active" | "deactivated";
        /**
         * Format: date-time
         * @description Canonical UTC instant with exactly six fractional digits and literal Z.
         */
        CanonicalUtcInstant: string;
        LocalWallTime: string;
        /** @description UTC offset from -14:00 through +14:00; 14-hour extremes require 00 minutes. */
        UtcOffset: string;
        OccurrenceCreate: {
            instant: components["schemas"]["CanonicalUtcInstant"];
            localWallTime: components["schemas"]["LocalWallTime"];
            utcOffset: components["schemas"]["UtcOffset"];
        };
        OccurrenceEdit: {
            /** @constant */
            mode: "preserve_offset";
            localWallTime: components["schemas"]["LocalWallTime"];
        } | {
            /** @constant */
            mode: "change_offset";
            localWallTime: components["schemas"]["LocalWallTime"];
            utcOffset: components["schemas"]["UtcOffset"];
            /** @constant */
            confirmation: "PRESERVE_WALL_TIME_AND_MOVE_INSTANT";
        };
        MoneyMemoCreateRequest: {
            /** Format: uuid */
            creationId: string;
            type: components["schemas"]["MoneyMemoType"];
            /** @description Positive canonical decimal string; zero rejected by domain. */
            amount: string;
            currency: string;
            occurrence: components["schemas"]["OccurrenceCreate"];
            /** Format: uuid */
            categoryId: string;
            /** Format: uuid */
            moneySpaceId: string;
            note?: string | null;
            plannedStatus: components["schemas"]["PlannedStatus"];
            purpose: components["schemas"]["Purpose"];
        };
        MoneyMemoEditRequest: {
            /** Format: int64 */
            expectedRevision: number;
            type: components["schemas"]["MoneyMemoType"];
            amount: string;
            currency: string;
            /** @enum {string|null} */
            currencyChangeConfirmation?: "REDECLARE_AMOUNT_WITHOUT_CONVERSION" | null;
            occurrence: components["schemas"]["OccurrenceEdit"];
            /** Format: uuid */
            categoryId: string;
            /** Format: uuid */
            moneySpaceId: string;
            note?: string | null;
            plannedStatus: components["schemas"]["PlannedStatus"];
            purpose: components["schemas"]["Purpose"];
        };
        RevisionRequest: {
            /** Format: int64 */
            expectedRevision: number;
        };
        MoneyMemo: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["MoneyMemoType"];
            amount: string;
            currency: string;
            amountMinorUnitScale: number;
            occurrence: {
                instant: components["schemas"]["CanonicalUtcInstant"];
                localWallTime: components["schemas"]["LocalWallTime"];
                utcOffset: components["schemas"]["UtcOffset"];
            };
            category: components["schemas"]["LabelReference"];
            moneySpace: components["schemas"]["LabelReference"];
            note: string | null;
            plannedStatus: components["schemas"]["PlannedStatus"];
            purpose: components["schemas"]["Purpose"];
            lifecycleStatus: components["schemas"]["LifecycleStatus"];
            purgeDeadline: components["schemas"]["CanonicalUtcInstant"] | null;
            /** Format: int64 */
            revision: number;
            createdAt: components["schemas"]["CanonicalUtcInstant"];
            updatedAt: components["schemas"]["CanonicalUtcInstant"];
        } & unknown;
        LabelReference: {
            /** Format: uuid */
            id: string;
            name: string;
            state: components["schemas"]["LabelState"];
        };
        Label: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["LabelKind"];
            name: string;
            state: components["schemas"]["LabelState"];
            /** Format: int64 */
            revision: number;
            createdAt: components["schemas"]["CanonicalUtcInstant"];
            updatedAt: components["schemas"]["CanonicalUtcInstant"];
        };
        PageRequest: {
            /** @default 50 */
            pageSize: number;
            pagePosition?: string | null;
            /** @description Required continuation version returned by preceding page; omitted on first page. */
            expectedResultSetVersion?: string | null;
        } & unknown;
        MoneyMemoQuery: {
            /** @default 50 */
            pageSize: number;
            pagePosition?: string | null;
            /** @description Required continuation version returned by preceding page; omitted on first page. */
            expectedResultSetVersion?: string | null;
            /** @description Trimmed; whitespace-only means no term. Multiple whitespace terms AND. */
            search?: string | null;
            /** Format: date */
            dateFrom?: string | null;
            /** Format: date */
            dateTo?: string | null;
            type?: components["schemas"]["MoneyMemoType"] | null;
            currency?: string | null;
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            moneySpaceId?: string | null;
            plannedStatus?: components["schemas"]["PlannedStatus"] | null;
            purpose?: components["schemas"]["Purpose"] | null;
            /**
             * @default active
             * @enum {string|null}
             */
            lifecycleStatus: "active" | "archived" | null;
        } & unknown;
        MoneyMemoPage: {
            items: components["schemas"]["MoneyMemo"][];
            nextPagePosition: string | null;
            /** @description Opaque version bound to page membership, order, view, and normalized query. */
            resultSetVersion: string;
        };
        /** @enum {string} */
        SafeDetectorId: "B1_PAN_LUHN" | "B2_IBAN_MOD97" | "B3_LABELED_ACCOUNT" | "B4_LABELED_ROUTING" | "B5_LABELED_CARD_SECRET" | "B6_LABELED_BANK_CREDENTIAL" | "B7_LABELED_BANK_TOKEN" | "B8_STATEMENT_PASTE" | "B9_LABELED_GOV_ID";
        FieldError: {
            field: string;
            rule: string;
            /** @description Never echoes submitted value */
            message: string;
            /** @description Published safe Pattern Set v1 ID only; never candidate content or derivative. */
            detectorId?: components["schemas"]["SafeDetectorId"] | null;
        };
        ErrorResponse: {
            /** @enum {string} */
            code: "AUTH_REQUIRED" | "NOT_FOUND" | "VALIDATION_FAILED" | "PRIVACY_INPUT_REJECTED" | "CREATION_IDENTIFIER_CONFLICT" | "REVISION_CONFLICT" | "CURRENCY_CHANGE_CONFIRMATION_REQUIRED" | "OFFSET_CHANGE_CONFIRMATION_REQUIRED" | "LABEL_NAME_CONFLICT" | "LABEL_IN_USE" | "EXPORT_IN_PROGRESS" | "EXPORT_CONSISTENCY_UNAVAILABLE" | "IDEMPOTENCY_VERIFICATION_UNAVAILABLE" | "PURGE_LEDGER_UNAVAILABLE" | "PAGE_POSITION_INVALID" | "PAGE_POSITION_EXPIRED" | "PAGE_SIZE_INVALID" | "LIST_CHANGED" | "DEPENDENCY_UNAVAILABLE";
            /** @description Stable safe message with no submitted values */
            message: string;
            /** Format: uuid */
            requestId: string;
            retryable: boolean;
            fieldErrors?: components["schemas"]["FieldError"][];
            /** @description Current same-owner resource for stale conflict; values are not part of message/log. */
            current?: components["schemas"]["MoneyMemo"] | components["schemas"]["Label"] | null;
            /**
             * Format: uuid
             * @description Same-owner ID only for creation identifier conflict.
             */
            existingMemoId?: string | null;
            refreshRequired?: boolean | null;
        };
        uuid: string;
        utcInstant: string;
        localWallTime: string;
        utcOffset: string;
        amount: {
            /** @description Exactly minorUnitScale fractional digits; scale 0 has no decimal point. */
            decimal: string;
            currency: string;
            minorUnitScale: number;
        } & (unknown & unknown & unknown & unknown & unknown);
        occurrence: {
            instant: components["schemas"]["utcInstant"];
            localWallTime: components["schemas"]["localWallTime"];
            utcOffset: components["schemas"]["utcOffset"];
        };
        reference: {
            id: components["schemas"]["uuid"];
            name: string;
            /** @enum {unknown} */
            state: "active" | "deactivated";
        };
        moneyMemo: {
            id: components["schemas"]["uuid"];
            /** @enum {unknown} */
            type: "income" | "expense";
            amount: components["schemas"]["amount"];
            occurrence: components["schemas"]["occurrence"];
            categoryId: components["schemas"]["uuid"];
            moneySpaceId: components["schemas"]["uuid"];
            note: string | null;
            /** @enum {unknown} */
            plannedStatus: "planned" | "unplanned";
            /** @enum {unknown} */
            purpose: "personal" | "work" | "mixed";
            /** @enum {unknown} */
            lifecycleStatus: "active" | "archived";
            createdAt: components["schemas"]["utcInstant"];
            updatedAt: components["schemas"]["utcInstant"];
        };
        /**
         * Cashmemo Money Memo Export v1
         * @description UTF-8 RFC 8259 JSON, no BOM, one trailing LF. Reference arrays sort by ID; moneyMemos sort by occurrence instant DESC, createdAt DESC, ID DESC. Object member order is not semantic. Pending-deletion records and internal owner, revision, creation, cursor, export-fence, deletion, fingerprint, key, and suppression metadata are forbidden by additionalProperties=false.
         */
        "export-v1.schema": {
            /** @constant */
            format: "cashmemo.money-memos";
            /** @constant */
            formatVersion: 1;
            acceptedAt: components["schemas"]["utcInstant"];
            includeArchived: boolean;
            /** @constant */
            currencyRegistry: "iso4217-list-one-2026-01-01";
            references: {
                categories: components["schemas"]["reference"][];
                moneySpaces: components["schemas"]["reference"][];
            };
            moneyMemos: components["schemas"]["moneyMemo"][];
            $defs: {
                uuid: string;
                utcInstant: string;
                localWallTime: string;
                utcOffset: string;
                reference: {
                    id: components["schemas"]["uuid"];
                    name: string;
                    /** @enum {unknown} */
                    state: "active" | "deactivated";
                };
                amount: {
                    /** @description Exactly minorUnitScale fractional digits; scale 0 has no decimal point. */
                    decimal: string;
                    currency: string;
                    minorUnitScale: number;
                } & (unknown & unknown & unknown & unknown & unknown);
                occurrence: {
                    instant: components["schemas"]["utcInstant"];
                    localWallTime: components["schemas"]["localWallTime"];
                    utcOffset: components["schemas"]["utcOffset"];
                };
                moneyMemo: {
                    id: components["schemas"]["uuid"];
                    /** @enum {unknown} */
                    type: "income" | "expense";
                    amount: components["schemas"]["amount"];
                    occurrence: components["schemas"]["occurrence"];
                    categoryId: components["schemas"]["uuid"];
                    moneySpaceId: components["schemas"]["uuid"];
                    note: string | null;
                    /** @enum {unknown} */
                    plannedStatus: "planned" | "unplanned";
                    /** @enum {unknown} */
                    purpose: "personal" | "work" | "mixed";
                    /** @enum {unknown} */
                    lifecycleStatus: "active" | "archived";
                    createdAt: components["schemas"]["utcInstant"];
                    updatedAt: components["schemas"]["utcInstant"];
                };
            };
        };
    };
    responses: {
        /** @description Missing, expired, or invalid Appwrite session; no resource data */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unknown, other-owner, expired, or purged resource; indistinguishable */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Stable domain conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description HTTP 422. Validation failures use VALIDATION_FAILED; structurally valid input rejected by Pattern Set v1 uses PRIVACY_INPUT_REJECTED. Neither form returns submitted values. */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Fail-closed retryable dependency/key/consistency failure */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        MemoId: string;
        LabelId: string;
    };
    requestBodies: never;
    headers: {
        NoStore: "no-store";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthenticatedSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated account used only to derive the one-way local draft partition */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    createMoneyMemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoneyMemoCreateRequest"];
            };
        };
        responses: {
            /** @description Matching retry; current memo returned with no mutation */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneyMemo"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneyMemo"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
            503: components["responses"]["Unavailable"];
        };
    };
    queryMoneyMemos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoneyMemoQuery"];
            };
        };
        responses: {
            /** @description Page in total descending order, bound to one result-set version */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneyMemoPage"];
                };
            };
            /** @description Result-set membership/order version changed; returned page must be discarded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    getMoneyMemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memoId: components["parameters"]["MemoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memo */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneyMemo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    editMoneyMemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memoId: components["parameters"]["MemoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoneyMemoEditRequest"];
            };
        };
        responses: {
            /** @description Updated memo, revision incremented once */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneyMemo"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Revision conflict, export fence, or required confirmation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    archiveMoneyMemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memoId: components["parameters"]["MemoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Archived, or idempotent current archived result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneyMemo"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    restoreArchivedMoneyMemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memoId: components["parameters"]["MemoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Active, or idempotent current active result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneyMemo"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    requestMoneyMemoDeletion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memoId: components["parameters"]["MemoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    expectedRevision: number;
                    /** @constant */
                    confirmation: "DELETE_TO_RECENTLY_DELETED";
                };
            };
        };
        responses: {
            /** @description Pending deletion; repeated request leaves original deadline unchanged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneyMemo"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    queryRecentlyDeleted: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageRequest"];
            };
        };
        responses: {
            /** @description Pending-deletion page */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneyMemoPage"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    restoreDeletedMoneyMemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memoId: components["parameters"]["MemoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Restored to pre-deletion lifecycle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneyMemo"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    purgeMoneyMemoNow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memoId: components["parameters"]["MemoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    expectedRevision: number;
                    /** @constant */
                    confirmation: "PERMANENTLY_PURGE_NOW";
                };
            };
        };
        responses: {
            /** @description Physically purged; no memo response exists */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    queryLabels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    kind: components["schemas"]["LabelKind"];
                    states: components["schemas"]["LabelState"][];
                };
            };
        };
        responses: {
            /** @description Owner labels; picker asks active only, filters ask both */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Label"][];
                    };
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    createLabel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    kind: components["schemas"]["LabelKind"];
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created active label */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    renameLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelId: components["parameters"]["LabelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    expectedRevision: number;
                    name: string;
                };
            };
        };
        responses: {
            /** @description Renamed same label ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    deactivateLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelId: components["parameters"]["LabelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Deactivated or idempotent current result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    reactivateLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelId: components["parameters"]["LabelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Active or idempotent current result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    permanentlyDeleteLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelId: components["parameters"]["LabelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    expectedRevision: number;
                    /** @constant */
                    confirmation: "PERMANENTLY_DELETE_LABEL";
                };
            };
        };
        responses: {
            /** @description Permanently deleted; reference count was zero */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    exportMoneyMemos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default false */
                    includeArchived: boolean;
                };
            };
        };
        responses: {
            /** @description Complete schema-valid export; never partial */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    /** @description attachment; filename="cashmemo-export-<acceptedAt>.json" */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.cashmemo.money-memo-export+json;version=1": components["schemas"]["export-v1.schema"];
                };
            };
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    getSupportedCurrencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pinned currency registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        version: "iso4217-list-one-2026-01-01";
                        /** @constant */
                        sourceEffectiveDate: "2026-01-01";
                        currencies: {
                            code: string;
                            minorUnitScale: number;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
