import type { PrivacyTrustBoundary } from "./contracts.js";

export interface PrivacyBoundaryDeclaration {
  readonly boundary: PrivacyTrustBoundary;
  readonly consentRequired: boolean;
  readonly detectorRequired: boolean;
  readonly diagnosticProhibition: true;
  readonly destination: string;
  readonly enforcingAdapter: string;
  readonly expectedBlockingResult: "PRIVACY_BOUNDARY_BLOCKED" | "RAW_VOICE_VALIDATION_BLOCKED";
  readonly persistenceAllowedAfterApproval: boolean;
  readonly providerTransmissionAllowedAfterApproval: boolean;
  readonly retentionClass:
    "current_operation_only" | "seven_day_draft" | "transient_query" | "user_owned" | "none";
  readonly source: string;
}

export const privacyBoundaryMatrix: readonly PrivacyBoundaryDeclaration[] = Object.freeze([
  {
    boundary: "device_draft_persistence",
    consentRequired: false,
    detectorRequired: true,
    diagnosticProhibition: true,
    destination: "account_scoped_indexeddb",
    enforcingAdapter: "apps/web/src/privacy/privacy-boundary.ts",
    expectedBlockingResult: "PRIVACY_BOUNDARY_BLOCKED",
    persistenceAllowedAfterApproval: true,
    providerTransmissionAllowedAfterApproval: false,
    retentionClass: "seven_day_draft",
    source: "browser_input",
  },
  {
    boundary: "server_draft_persistence",
    consentRequired: false,
    detectorRequired: true,
    diagnosticProhibition: true,
    destination: "compose_drafts",
    enforcingAdapter: "apps/server/src/modules/privacy/privacy-boundary.service.ts",
    expectedBlockingResult: "PRIVACY_BOUNDARY_BLOCKED",
    persistenceAllowedAfterApproval: true,
    providerTransmissionAllowedAfterApproval: false,
    retentionClass: "seven_day_draft",
    source: "user_input",
  },
  {
    boundary: "typed_text_ai_transmission",
    consentRequired: true,
    detectorRequired: true,
    diagnosticProhibition: true,
    destination: "extraction_provider",
    enforcingAdapter: "apps/server/src/modules/assisted-capture/text-extraction.service.ts",
    expectedBlockingResult: "PRIVACY_BOUNDARY_BLOCKED",
    persistenceAllowedAfterApproval: false,
    providerTransmissionAllowedAfterApproval: true,
    retentionClass: "current_operation_only",
    source: "typed_text",
  },
  {
    boundary: "raw_voice_stt_transmission",
    consentRequired: true,
    detectorRequired: false,
    diagnosticProhibition: true,
    destination: "stt_provider",
    enforcingAdapter: "apps/server/src/modules/assisted-capture/voice-capture.service.ts",
    expectedBlockingResult: "RAW_VOICE_VALIDATION_BLOCKED",
    persistenceAllowedAfterApproval: false,
    providerTransmissionAllowedAfterApproval: true,
    retentionClass: "current_operation_only",
    source: "current_recording",
  },
  {
    boundary: "transcript_persistence",
    consentRequired: false,
    detectorRequired: true,
    diagnosticProhibition: true,
    destination: "compose_drafts",
    enforcingAdapter: "apps/server/src/modules/assisted-capture/transcript.service.ts",
    expectedBlockingResult: "PRIVACY_BOUNDARY_BLOCKED",
    persistenceAllowedAfterApproval: true,
    providerTransmissionAllowedAfterApproval: false,
    retentionClass: "seven_day_draft",
    source: "stt_transcript",
  },
  {
    boundary: "transcript_ai_transmission",
    consentRequired: true,
    detectorRequired: true,
    diagnosticProhibition: true,
    destination: "extraction_provider",
    enforcingAdapter: "apps/server/src/modules/assisted-capture/transcript.service.ts",
    expectedBlockingResult: "PRIVACY_BOUNDARY_BLOCKED",
    persistenceAllowedAfterApproval: false,
    providerTransmissionAllowedAfterApproval: true,
    retentionClass: "current_operation_only",
    source: "stt_transcript",
  },
  {
    boundary: "memo_note_persistence",
    consentRequired: false,
    detectorRequired: true,
    diagnosticProhibition: true,
    destination: "money_memos",
    enforcingAdapter: "apps/server/src/modules/assisted-capture/confirm-draft.service.ts",
    expectedBlockingResult: "PRIVACY_BOUNDARY_BLOCKED",
    persistenceAllowedAfterApproval: true,
    providerTransmissionAllowedAfterApproval: false,
    retentionClass: "user_owned",
    source: "memo_note",
  },
  {
    boundary: "label_persistence",
    consentRequired: false,
    detectorRequired: true,
    diagnosticProhibition: true,
    destination: "categories_or_money_spaces",
    enforcingAdapter: "apps/server/src/modules/labels/labels.service.ts",
    expectedBlockingResult: "PRIVACY_BOUNDARY_BLOCKED",
    persistenceAllowedAfterApproval: true,
    providerTransmissionAllowedAfterApproval: false,
    retentionClass: "user_owned",
    source: "custom_label",
  },
  {
    boundary: "search_execution",
    consentRequired: false,
    detectorRequired: true,
    diagnosticProhibition: true,
    destination: "postgres_bound_query",
    enforcingAdapter: "apps/server/src/modules/history/search.repository.ts",
    expectedBlockingResult: "PRIVACY_BOUNDARY_BLOCKED",
    persistenceAllowedAfterApproval: false,
    providerTransmissionAllowedAfterApproval: false,
    retentionClass: "transient_query",
    source: "search_text",
  },
  {
    boundary: "support_capture",
    consentRequired: false,
    detectorRequired: true,
    diagnosticProhibition: true,
    destination: "typed_support_adapter",
    enforcingAdapter: "apps/server/src/adapters/telemetry/safe-telemetry.ts",
    expectedBlockingResult: "PRIVACY_BOUNDARY_BLOCKED",
    persistenceAllowedAfterApproval: false,
    providerTransmissionAllowedAfterApproval: false,
    retentionClass: "none",
    source: "support_signal",
  },
  {
    boundary: "evidence_capture",
    consentRequired: false,
    detectorRequired: true,
    diagnosticProhibition: true,
    destination: "typed_evidence_writer",
    enforcingAdapter: "packages/test-support/src/evidence/evidence-writer.ts",
    expectedBlockingResult: "PRIVACY_BOUNDARY_BLOCKED",
    persistenceAllowedAfterApproval: false,
    providerTransmissionAllowedAfterApproval: false,
    retentionClass: "none",
    source: "evidence_input",
  },
]);
