[package]
name = "domain"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
sea-orm = { version = "2", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono", "with-uuid"] }
sea-orm-migration = { version = "2", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
serde = { version = "1", features = ["derive"] }
